name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    concurrency:
      group: build-global-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 7

      - name: Login to Docker [ap-southeast-1]
        uses: docker/login-action@v2
        with:
          registry: registry.ap-southeast-1.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image and push [ap-southeast-1]
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: registry.ap-southeast-1.aliyuncs.com/kemono/maintenance:main-${{ env.SHA }}
          file: Dockerfile

      - name: Login to Docker [cn-shenzhen]
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image and push [cn-shenzhen]
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: registry.cn-shenzhen.aliyuncs.com/kemono/maintenance:main-${{ env.SHA }}
          file: Dockerfile
